### ISSUE TITLE
Import error with python 3

### ISSUE THREAD

**Issue by PiRune** [python-greenlet/greenlet#107]
Hi all. Noob here.

I simply can't get greenlet to work with python 3

I tried reinstalling greenlet this way:
`sudo pip install greenlet --target=/usr/local/lib/python3.4/dist-packages/`

but I still can't get it to work. I keep getting the greenlet import error (undefined symbol: _Py_ZeroStruct). 

```
pi@raspberrypi:~ $ python3
Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import greenlet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/python3.4/dist-packages/greenlet.so: undefined symbol: _Py_ZeroStruct
>>> 
```

when I use python 2.7 i get no error:

```
pi@raspberrypi:~ $ python
Python 2.7.9 (default, Mar  8 2015, 00:52:26) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import greenlet
>>> greenlet
<module 'greenlet' from '/usr/local/lib/python2.7/dist-packages/greenlet-0.4.10-py2.7-linux-armv7l.egg/greenlet.so'>
>>> 
```

Can anyone help me solve this issue?

**Comment by snaury** [comment]
I'm not sure what could have gone wrong, please check if this helps:

```
sudo pip3 install -U --force-reinstall --no-binary :all: greenlet
```

**Comment by PiRune** [comment]
Hi Snaury

When I try, I get the following error

```
pi@raspberrypi:~ $ sudo pip3 install -U --force-reinstall --no-binary :all: greenlet
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip3')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # nova
  File "/usr/lib/python3/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python3/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name 'IncompleteRead'
```

**Comment by snaury** [comment]
I think you have problems with pip and how you installed packages in the past, not with greenlet. To install something for python 3 you should have always used `pip3`, not `pip` (the latter is usually for python 2).

**Comment by PiRune** [comment]
You are right. Tried "sudo pip 3 install..." and it works :)
