### ISSUE TITLE
Socket times-out and throws error

### ISSUE THREAD

**Issue by jsbroks** [python-greenlet/greenlet#144]
Not sure if this is related to greenlet or eventlet, I hope you can redirect me if need be.
```
[2019-03-16 02:24:05 +0000] [9] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py",                                                                   line 66, in handle
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/gunicorn/six.py", line 625, in re                                                                  raise
    raise value
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py",                                                                   line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py",                                                                   line 129, in handle_request
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/gunicorn/six.py", line 625, in re                                                                  raise
    raise value
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py",                                                                   line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __ca                                                                  ll__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line                                                                   44, in __call__
    start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/middleware.py", line 59,                                                                   in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 428, in                                                                   handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/server.py", line 340, in                                                                   handle_request
    environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 106, in                                                                   handle_get_request
    start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 146, in                                                                   _upgrade_websocket
    return ws(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/async_drivers/eventlet.p                                                                  y", line 20, in __call__
    return super(WebSocketWSGI, self).__call__(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/eventlet/websocket.py", line 130,                                                                   in __call__
    self.handler(ws)
  File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 172, in                                                                   _websocket_handler
    pkt = ws.wait()
  File "/usr/local/lib/python3.6/site-packages/eventlet/websocket.py", line 788,                                                                   in wait
    for i in self.iterator:
  File "/usr/local/lib/python3.6/site-packages/eventlet/websocket.py", line 643,                                                                   in _iter_frames
    message = self._recv_frame(message=fragmented_message)
  File "/usr/local/lib/python3.6/site-packages/eventlet/websocket.py", line 669,                                                                   in _recv_frame
    header = recv(2)
  File "/usr/local/lib/python3.6/site-packages/eventlet/websocket.py", line 578,                                                                   in _get_bytes
    d = self.socket.recv(numbytes - len(data))
  File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 3                                                                  64, in recv
    return self._recv_loop(self.fd.recv, b'', bufsize, flags)
  File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 3                                                                  58, in _recv_loop
    self._read_trampoline()
  File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 3                                                                  29, in _read_trampoline
    timeout_exc=socket_timeout('timed out'))
  File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 2                                                                  08, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/usr/local/lib/python3.6/site-packages/eventlet/hubs/__init__.py", line                                                                   164, in trampoline
    return hub.switch()
  File "/usr/local/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 297,                                                                   in switch
    return self.greenlet.switch()
socket.timeout: timed out
```

**Comment by jamadden** [comment]
If this is still an issue, I suggest bringing it up on the `eventlet` tracker. greenlet knows nothing about sockets, that layer is far above it.
