### ISSUE TITLE
Introducing greenlet causes failures in pytest test suite

### ISSUE THREAD

**Issue by di** [python-greenlet/greenlet#243]
Hi there! We use `sqlalchemy` as a dependency and `sqlalchemy>1.4.0` introduces `greenlet==1.0.0` as a sub-dependency.

Introducing `greenlet` into our CI environment seems to cause pytest to fail to invoke with the following traceback:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1183, in _preparse
    self.issue_config_time_warning(
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1320, in issue_config_time_warning
    apply_warning_filters(config_filters, cmdline_filters)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1603, in apply_warning_filters
    warnings.filterwarnings(*parse_warning_filter(arg, escape=False))
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1579, in parse_warning_filter
Warning: ory: Type[Warning] = warnings._getcategory(category_)  # type: ignore[attr-defined]
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/warnings.py", line 262, in _getcategory
    raise _OptionError("invalid module name: %r" % (module,)) from None
warnings._OptionError: invalid module name: 'warehouse.packaging.services'
```

I'm aware that greenlet does some monkeypatching of the stdlib, which leads me to report this here and not  with sqlalchemy. Is it possible greenlet is the culprit?

(You can see a failing test run here: https://github.com/pypa/warehouse/runs/2129386764 and the PR that caused the failure here: https://github.com/pypa/warehouse/pull/9228)

**Comment by jamadden** [comment]
Hi @di ! Greenlet actually does *not* do any monkey patching. It’s entirely independent and only does anything when explicitly invoked. Perhaps you’re thinking of gevent’s optional monkey patching.

**Comment by di** [comment]
Looks like this is the result of future Python 3.9 behavior brought in by sqlalchemy. Thanks!
