### ISSUE TITLE
1.1.1:  nosetests and pytest are failing

### ISSUE THREAD

**Issue by kloczek** [python-greenlet/greenlet#254]
I'm trying to package your module as rpm packag. So I'm using typical in such case build, install and test cycle used on building package from non-root account:
- "setup.py build"
- "setup.py install --root </install/prefix>"
- "pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

May I ask for help because few units are failing:
```console
+ cd /home/tkloczko/rpmbuild/BUILD
+ cd greenlet-1.1.1
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages
+ nosetests
E
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'greenlet._greenlet')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.8/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib64/python3.8/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib64/python3.8/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tkloczko/rpmbuild/BUILD/greenlet-1.1.1/src/greenlet/__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ModuleNotFoundError: No module named 'greenlet._greenlet'

----------------------------------------------------------------------
Ran 1 test in 0.007s

FAILED (errors=1)
```
Looks like test suite relies on some private module which is not part of the istalled resources.

With pytest is even worse:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.1
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, toolbox-0.5, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, pyfakefs-4.5.0, flaky-3.7.0, benchmark-3.4.1, xdist-2.3.0, pylama-7.7.1, datadir-1.3.1, regressions-2.2.0, cases-3.6.3, hypothesis-6.14.4, xprocess-0.18.1, black-0.3.12, checkdocs-2.7.1, anyio-3.3.0, Faker-8.11.0, asyncio-0.15.1, trio-0.7.0, httpbin-1.0.0, subtests-0.5.0
collected 2 items / 13 errors

================================================================================== ERRORS ==================================================================================
_________________________________________________________ ERROR collecting src/greenlet/tests/test_contextvars.py __________________________________________________________
import file mismatch:
imported module 'greenlet.tests.test_contextvars' has this __file__ attribute:
  /home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_contextvars.py
which is not the same as the test file we want to collect:
  /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.1/src/greenlet/tests/test_contextvars.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
_____________________________________________________________ ERROR collecting src/greenlet/tests/test_cpp.py ______________________________________________________________
import file mismatch:
imported module 'greenlet.tests.test_cpp' has this __file__ attribute:
  /home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_cpp.py
which is not the same as the test file we want to collect:
  /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.1/src/greenlet/tests/test_cpp.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
_____________________________________________________ ERROR collecting src/greenlet/tests/test_extension_interface.py ______________________________________________________
import file mismatch:
imported module 'greenlet.tests.test_extension_interface' has this __file__ attribute:
  /home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_extension_interface.py
which is not the same as the test file we want to collect:
  /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.1/src/greenlet/tests/test_extension_interface.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
______________________________________________________________ ERROR collecting src/greenlet/tests/test_gc.py ______________________________________________________________
import file mismatch:
imported module 'greenlet.tests.test_gc' has this __file__ attribute:
  /home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_gc.py
which is not the same as the test file we want to collect:
  /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.1/src/greenlet/tests/test_gc.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
__________________________________________________________ ERROR collecting src/greenlet/tests/test_generator.py ___________________________________________________________
import file mismatch:
imported module 'greenlet.tests.test_generator' has this __file__ attribute:
  /home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_generator.py
which is not the same as the test file we want to collect:
  /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.1/src/greenlet/tests/test_generator.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
_______________________________________________________ ERROR collecting src/greenlet/tests/test_generator_nested.py _______________________________________________________
import file mismatch:
imported module 'greenlet.tests.test_generator_nested' has this __file__ attribute:
  /home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_generator_nested.py
which is not the same as the test file we want to collect:
  /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.1/src/greenlet/tests/test_generator_nested.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
___________________________________________________________ ERROR collecting src/greenlet/tests/test_greenlet.py ___________________________________________________________
import file mismatch:
imported module 'greenlet.tests.test_greenlet' has this __file__ attribute:
  /home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_greenlet.py
which is not the same as the test file we want to collect:
  /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.1/src/greenlet/tests/test_greenlet.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
____________________________________________________________ ERROR collecting src/greenlet/tests/test_leaks.py _____________________________________________________________
import file mismatch:
imported module 'greenlet.tests.test_leaks' has this __file__ attribute:
  /home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_leaks.py
which is not the same as the test file we want to collect:
  /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.1/src/greenlet/tests/test_leaks.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
_________________________________________________________ ERROR collecting src/greenlet/tests/test_stack_saved.py __________________________________________________________
import file mismatch:
imported module 'greenlet.tests.test_stack_saved' has this __file__ attribute:
  /home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_stack_saved.py
which is not the same as the test file we want to collect:
  /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.1/src/greenlet/tests/test_stack_saved.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
____________________________________________________________ ERROR collecting src/greenlet/tests/test_throw.py _____________________________________________________________
import file mismatch:
imported module 'greenlet.tests.test_throw' has this __file__ attribute:
  /home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_throw.py
which is not the same as the test file we want to collect:
  /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.1/src/greenlet/tests/test_throw.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
___________________________________________________________ ERROR collecting src/greenlet/tests/test_tracing.py ____________________________________________________________
import file mismatch:
imported module 'greenlet.tests.test_tracing' has this __file__ attribute:
  /home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_tracing.py
which is not the same as the test file we want to collect:
  /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.1/src/greenlet/tests/test_tracing.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
___________________________________________________________ ERROR collecting src/greenlet/tests/test_version.py ____________________________________________________________
import file mismatch:
imported module 'greenlet.tests.test_version' has this __file__ attribute:
  /home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_version.py
which is not the same as the test file we want to collect:
  /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.1/src/greenlet/tests/test_version.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
___________________________________________________________ ERROR collecting src/greenlet/tests/test_weakref.py ____________________________________________________________
import file mismatch:
imported module 'greenlet.tests.test_weakref' has this __file__ attribute:
  /home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_weakref.py
which is not the same as the test file we want to collect:
  /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.1/src/greenlet/tests/test_weakref.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
========================================================================= short test summary info ==========================================================================
ERROR src/greenlet/tests/test_contextvars.py
ERROR src/greenlet/tests/test_cpp.py
ERROR src/greenlet/tests/test_extension_interface.py
ERROR src/greenlet/tests/test_gc.py
ERROR src/greenlet/tests/test_generator.py
ERROR src/greenlet/tests/test_generator_nested.py
ERROR src/greenlet/tests/test_greenlet.py
ERROR src/greenlet/tests/test_leaks.py
ERROR src/greenlet/tests/test_stack_saved.py
ERROR src/greenlet/tests/test_throw.py
ERROR src/greenlet/tests/test_tracing.py
ERROR src/greenlet/tests/test_version.py
ERROR src/greenlet/tests/test_weakref.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 13 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================ 13 errors in 0.26s ============================================================================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
```

**Comment by jamadden** [comment]
This package uses the standard library `unittest` module. Please see `tox.ini` or `tests.yml` or even `appveyor.yml` for the way it is tested. Most people should test it by simply using `tox`.

**Comment by kloczek** [comment]
It would be rally noce to to have possibily to use pytaest without venv to be able to use pytaest with some extensions.
Pytest can use unittest description to perform tatst.
Can you point on some parts of the `greenlet` code which forces use evnv on testing?
As I have whole framework which I'm using to perform test builds against specified modules I would be rally interested to patch `greenlet` code to be able use pytest without even if you would be not interested such patch.

Thx

**Comment by kloczek** [comment]
Issue is that pytest can handle `unittest` however looks like there some coding methodologies issues. Some of the issues can be solved by use `--import-mode=importlib --pyargs greenlet.tests` pytest params.
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.2-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra --import-mode=importlib --pyargs greenlet.tests src/greenlet/tests
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
Using --randomly-seed=1885532442
rootdir: /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.2
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, aspectlib-1.5.2, toolbox-0.5, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, flaky-3.7.0, benchmark-3.4.1, xdist-2.3.0, pylama-7.7.1, datadir-1.3.1, regressions-2.2.0, xprocess-0.18.1, black-0.3.12, asyncio-0.15.1, subtests-0.5.0, isort-2.0.0, hypothesis-6.14.6, mock-3.6.1, profiling-1.7.0, randomly-3.8.0, nose2pytest-1.0.8, pyfakefs-4.5.1, tornado-0.8.1, twisted-1.13.3, aiohttp-0.3.0, localserver-0.5.0, anyio-3.3.1, trio-0.7.0, cases-3.6.4, yagot-0.5.0, Faker-8.14.0
collected 162 items / 4 errors / 158 selected

================================================================================== ERRORS ==================================================================================
_______________________________________________________________________ ERROR collecting test_cpp.py _______________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_cpp.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../BUILDROOT/python-greenlet-1.1.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_cpp.py:7: in <module>
    from . import _test_extension_cpp
E   ImportError: attempted relative import with no known parent package
_______________________________________________________________ ERROR collecting test_extension_interface.py _______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-1.1.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_extension_interface.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../BUILDROOT/python-greenlet-1.1.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/test_extension_interface.py:8: in <module>
    from . import _test_extension
E   ImportError: attempted relative import with no known parent package
_____________________________________________________________ ERROR collecting src/greenlet/tests/test_cpp.py ______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/greenlet-1.1.2/src/greenlet/tests/test_cpp.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/greenlet/tests/test_cpp.py:7: in <module>
    from . import _test_extension_cpp
E   ImportError: attempted relative import with no known parent package
_____________________________________________________ ERROR collecting src/greenlet/tests/test_extension_interface.py ______________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/greenlet-1.1.2/src/greenlet/tests/test_extension_interface.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/greenlet/tests/test_extension_interface.py:8: in <module>
    from . import _test_extension
E   ImportError: attempted relative import with no known parent package
========================================================================= short test summary info ==========================================================================
ERROR test_cpp.py
ERROR test_extension_interface.py
ERROR src/greenlet/tests/test_cpp.py
ERROR src/greenlet/tests/test_extension_interface.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================ 4 errors in 0.58s =============================================================================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
```

**Comment by kloczek** [comment]
And just tested on 1.1.2 tox and looks like it fails as well.
```console
+ /usr/bin/tox --skip-missing-interpreters
GLOB sdist-make: /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.2/setup.py
py27 create: /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.2/.tox/py27
SKIPPED: InterpreterNotFound: python2.7
py35 create: /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.2/.tox/py35
SKIPPED: InterpreterNotFound: python3.5
py36 create: /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.2/.tox/py36
SKIPPED: InterpreterNotFound: python3.6
py37 create: /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.2/.tox/py37
SKIPPED: InterpreterNotFound: python3.7
py38 create: /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.2/.tox/py38
ERROR: invocation failed (exit code 1), logfile: /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.2/.tox/py38/log/py38-0.log
================================================================================ log start =================================================================================
RuntimeError: failed to build image wheel because:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 51, in _install
    key = Path(installer_class.__name__) / wheel.path.stem
AttributeError: 'NoneType' object has no attribute 'path'


================================================================================= log end ==================================================================================
ERROR: InvocationError for command /usr/bin/python3 -m virtualenv --no-download --python /usr/bin/python3 py38 (exited with code 1)
py39 create: /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.2/.tox/py39
SKIPPED: InterpreterNotFound: python3.9
py310 create: /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.2/.tox/py310
SKIPPED: InterpreterNotFound: python3.10
docs create: /home/tkloczko/rpmbuild/BUILD/greenlet-1.1.2/.tox/docs
SKIPPED: InterpreterNotFound: python3.9
_________________________________________________________________________________ summary __________________________________________________________________________________
SKIPPED:  py27: InterpreterNotFound: python2.7
SKIPPED:  py35: InterpreterNotFound: python3.5
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
ERROR:   py38: InvocationError for command /usr/bin/python3 -m virtualenv --no-download --python /usr/bin/python3 py38 (exited with code 1)
SKIPPED:  py39: InterpreterNotFound: python3.9
SKIPPED:  py310: InterpreterNotFound: python3.10
SKIPPED:  docs: InterpreterNotFound: python3.9
```

**Comment by DigitalJacob** [comment]
Hello, I have the same problem in PyCharm:

from ._greenlet import _C_API # pylint:disable=no-name-in-module
ModuleNotFoundError: No module named

Have you already solved this problem?
