### ISSUE TITLE
Tests do not run in source directory

### ISSUE THREAD

**Issue by Biswa96** [python-greenlet/greenlet#289]
After building, if I run `python -m unittest discover -v greenlet.tests` command the following error is shown:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.9/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.9/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.9/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.9/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.9/unittest/loader.py", line 346, in discover
    raise ImportError('Start directory is not importable: %r' % start_dir)
ImportError: Start directory is not importable: 'greenlet.tests'
```

Tested with Python 3.9.10 in Ubuntu and Python 3.10.2 in ArchLinux. Same result. How can I run tests in current source directory after building?

**Comment by jamadden** [comment]
If you're not going to install the package, you need to make sure it's on the Python path, and you have to ask the test runner to discover tests in the filesystem instead of installed modules:

```console
$ git clone python-greenlet/greenlet
Cloning into 'greenlet'...
remote: Enumerating objects: 3914, done.
remote: Counting objects: 100% (1804/1804), done.
remote: Compressing objects: 100% (446/446), done.
remote: Total 3914 (delta 1181), reused 1671 (delta 1085), pack-reused 2110
Receiving objects: 100% (3914/3914), 1.35 MiB | 7.11 MiB/s, done.
Resolving deltas: 100% (2530/2530), done.
$ cd ./greenlet
$ python3.10 setup.py build_ext -i
running build_ext
creating build
creating build/temp.macosx-11.0-x86_64-3.10
creating build/temp.macosx-11.0-x86_64-3.10/src
creating build/temp.macosx-11.0-x86_64-3.10/src/greenlet
...

$ PYTHONPATH=src python3.10 -m unittest discover src
E
======================================================================
ERROR: greenlet.tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: greenlet.tests
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/private/tmp/greenlet/src/greenlet/tests/__init__.py", line 24, in <module>
    from . import leakcheck
  File "/private/tmp/greenlet/src/greenlet/tests/leakcheck.py", line 34, in <module>
    import objgraph
ModuleNotFoundError: No module named 'objgraph'

———————————————————————————————————
```

Of course, as you can see, you still need to install the proper test dependencies as found in the `test` extra. For example:

```console
$ python3.10 -m venv .venv
$ . .venv/bin/activate
(.venv) $ python -m pip install -U -e .[test]
Obtaining file:///private/tmp/greenlet
Collecting objgraph
  Using cached objgraph-3.5.0-py2.py3-none-any.whl (17 kB)
Collecting graphviz
  Using cached graphviz-0.19.1-py3-none-any.whl (46 kB)
Installing collected packages: graphviz, objgraph, greenlet
  Running setup.py develop for greenlet
Successfully installed graphviz-0.19.1 greenlet-2.0.0a2.dev0 objgraph-3.5.0
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/private/tmp/greenlet/.venv/bin/python -m pip install --upgrade pip' command.
(.venv) $ python -m unittest discover -v greenlet.tests
test_break_ctxvars (greenlet.tests.test_contextvars.ContextVarsTests) ... ok
test_context_assignment_different_thread (greenlet.tests.test_contextvars.ContextVarsTests) ... ok
test_context_assignment_while_running (greenlet.tests.test_contextvars.ContextVarsTests) … ok
…
```
