### ISSUE TITLE
greenlet.greenlet size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by komalbarun** [python-greenlet/greenlet#299]
Ubuntu 22.04
Python 3.10.4
gevent 21.1.2
greenlet 1.1.2

Apr 28 09:02:08 ProdEvo22 systemd[1]: Starting Ajenti panel...
Apr 28 09:02:08 ProdEvo22 python3[40388]: <frozen importlib._bootstrap>:241: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 160 from PyObject
Apr 28 09:02:08 ProdEvo22 python3[40388]: <frozen importlib._bootstrap>:241: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 160 from PyObject
Apr 28 09:02:08 ProdEvo22 python3[40388]: <frozen importlib._bootstrap>:241: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 160 from PyObject
Apr 28 09:02:08 ProdEvo22 python3[40388]: <frozen importlib._bootstrap>:241: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 160 from PyObject
Apr 28 09:02:08 ProdEvo22 python3[40388]: <frozen importlib._bootstrap>:241: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 160 from PyObject
Apr 28 09:02:13 ProdEvo22 systemd[1]: ajenti.service: New main PID 40391 does not exist or is a zombie.
Apr 28 09:02:13 ProdEvo22 systemd[1]: ajenti.service: Failed with result 'protocol'.
Apr 28 09:02:13 ProdEvo22 systemd[1]: Failed to start Ajenti panel.
Apr 28 09:02:13 ProdEvo22 systemd[1]: ajenti.service: Consumed 1.107s CPU time.

**Comment by jamadden** [comment]
Please try the latest versions of both gevent and greenlet.

**Comment by teebszet** [comment]
is this happening again with latest version?

macOS 12.6
Python 3.10.0
greenlet 2.0.2
gevent 22.10.2

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/locust", line 5, in <module>
    from locust.main import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/locust/__init__.py", line 9, in <module>
    from gevent import monkey
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gevent/_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/_hub_local.py", line 1, in init gevent._gevent_c_hub_local
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 160 from C header, got 40 from PyObject
```

**Comment by preetham-salehundam** [comment]
@jamadden - I have the same issue as the one above. Can you please guide on how to proceed?
