### ISSUE TITLE
2.0.2: pytest is failing in one unit and because are used relative imports

### ISSUE THREAD

**Issue by kloczek** [python-greenlet/greenlet#360]
I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix> using 'installer` module
- run pytest with $PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>
- build is performed in env which is *`cut off from access to the public network`* (pytest is executed with `-m "not network"`)

On using above methodology pytest is failing because are used relative imports (which using as usually is nothing more than asking for trouubles)
<details>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-2.0.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-2.0.2-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -m 'not network' --import-mode=importlib
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.8.17, pytest-7.3.1, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2
collected 2 items / 12 errors

========================================================================================== ERRORS ===========================================================================================
__________________________________________________________________ ERROR collecting src/greenlet/tests/test_contextvars.py __________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_contextvars.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/greenlet/tests/test_contextvars.py:12: in <module>
    from . import TestCase
E   ModuleNotFoundError: No module named 'src'
______________________________________________________________________ ERROR collecting src/greenlet/tests/test_cpp.py ______________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_cpp.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/greenlet/tests/test_cpp.py:8: in <module>
    from . import _test_extension_cpp
E   ModuleNotFoundError: No module named 'src'
______________________________________________________________ ERROR collecting src/greenlet/tests/test_extension_interface.py ______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_extension_interface.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/greenlet/tests/test_extension_interface.py:7: in <module>
    from . import _test_extension
E   ModuleNotFoundError: No module named 'src'
______________________________________________________________________ ERROR collecting src/greenlet/tests/test_gc.py _______________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_gc.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/greenlet/tests/test_gc.py:8: in <module>
    from . import TestCase
E   ModuleNotFoundError: No module named 'src'
___________________________________________________________________ ERROR collecting src/greenlet/tests/test_generator.py ___________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_generator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/greenlet/tests/test_generator.py:4: in <module>
    from . import TestCase
E   ModuleNotFoundError: No module named 'src'
_______________________________________________________________ ERROR collecting src/greenlet/tests/test_generator_nested.py ________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_generator_nested.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/greenlet/tests/test_generator_nested.py:3: in <module>
    from . import TestCase
E   ModuleNotFoundError: No module named 'src'
___________________________________________________________________ ERROR collecting src/greenlet/tests/test_greenlet.py ____________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_greenlet.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/greenlet/tests/test_greenlet.py:13: in <module>
    from . import TestCase
E   ModuleNotFoundError: No module named 'src'
_____________________________________________________________________ ERROR collecting src/greenlet/tests/test_leaks.py _____________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_leaks.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/greenlet/tests/test_leaks.py:17: in <module>
    from . import TestCase
E   ImportError: cannot import name 'TestCase' from 'src.greenlet.tests' (unknown location)
__________________________________________________________________ ERROR collecting src/greenlet/tests/test_stack_saved.py __________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_stack_saved.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/greenlet/tests/test_stack_saved.py:2: in <module>
    from . import TestCase
E   ImportError: cannot import name 'TestCase' from 'src.greenlet.tests' (unknown location)
_____________________________________________________________________ ERROR collecting src/greenlet/tests/test_throw.py _____________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_throw.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/greenlet/tests/test_throw.py:5: in <module>
    from . import TestCase
E   ImportError: cannot import name 'TestCase' from 'src.greenlet.tests' (unknown location)
____________________________________________________________________ ERROR collecting src/greenlet/tests/test_tracing.py ____________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_tracing.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/greenlet/tests/test_tracing.py:5: in <module>
    from . import TestCase
E   ImportError: cannot import name 'TestCase' from 'src.greenlet.tests' (unknown location)
____________________________________________________________________ ERROR collecting src/greenlet/tests/test_weakref.py ____________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_weakref.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/greenlet/tests/test_weakref.py:6: in <module>
    from . import TestCase
E   ImportError: cannot import name 'TestCase' from 'src.greenlet.tests' (unknown location)
================================================================================== short test summary info ==================================================================================
ERROR src/greenlet/tests/test_contextvars.py
ERROR src/greenlet/tests/test_cpp.py
ERROR src/greenlet/tests/test_extension_interface.py
ERROR src/greenlet/tests/test_gc.py
ERROR src/greenlet/tests/test_generator.py
ERROR src/greenlet/tests/test_generator_nested.py
ERROR src/greenlet/tests/test_greenlet.py
ERROR src/greenlet/tests/test_leaks.py
ERROR src/greenlet/tests/test_stack_saved.py
ERROR src/greenlet/tests/test_throw.py
ERROR src/greenlet/tests/test_tracing.py
ERROR src/greenlet/tests/test_weakref.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 12 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================================================================== 12 errors in 0.23s =====================================================================================
```
</details>

Here is patch which removes use relative imports
```patch
--- a/src/greenlet/tests/test_extension_interface.py
+++ b/src/greenlet/tests/test_extension_interface.py
@@ -4,8 +4,8 @@
 import sys

 import greenlet
-from . import _test_extension
-from . import TestCase
+from greenlet.tests import _test_extension
+from greenlet.tests import TestCase

 # pylint:disable=c-extension-no-member

--- a/src/greenlet/tests/test_cpp.py
+++ b/src/greenlet/tests/test_cpp.py
@@ -5,8 +5,8 @@
 from multiprocessing import Process

 import greenlet
-from . import _test_extension_cpp
-from . import TestCase
+from greenlet.tests import _test_extension_cpp
+from greenlet.tests import TestCase

 def run_unhandled_exception_in_greenlet_aborts():
     # This is used in multiprocessing.Process and must be picklable
--- a/src/greenlet/tests/test_weakref.py
+++ b/src/greenlet/tests/test_weakref.py
@@ -3,7 +3,7 @@
 import unittest

 import greenlet
-from . import TestCase
+from greenlet.tests import TestCase

 class WeakRefTests(TestCase):
     def test_dead_weakref(self):
--- a/src/greenlet/tests/test_tracing.py
+++ b/src/greenlet/tests/test_tracing.py
@@ -2,7 +2,7 @@
 import sys
 import greenlet

-from . import TestCase
+from greenlet.tests import TestCase

 class SomeError(Exception):
     pass
--- a/src/greenlet/tests/test_throw.py
+++ b/src/greenlet/tests/test_throw.py
@@ -2,7 +2,7 @@


 from greenlet import greenlet
-from . import TestCase
+from greenlet.tests import TestCase

 def switch(*args):
     return greenlet.getcurrent().parent.switch(*args)
--- a/src/greenlet/tests/test_stack_saved.py
+++ b/src/greenlet/tests/test_stack_saved.py
@@ -1,5 +1,5 @@
 import greenlet
-from . import TestCase
+from greenlet.tests import TestCase


 class Test(TestCase):
--- a/src/greenlet/tests/test_leaks.py
+++ b/src/greenlet/tests/test_leaks.py
@@ -14,11 +14,11 @@
 import psutil

 import greenlet
-from . import TestCase
-from .leakcheck import fails_leakcheck
-from .leakcheck import ignores_leakcheck
-from .leakcheck import RUNNING_ON_GITHUB_ACTIONS
-from .leakcheck import RUNNING_ON_MANYLINUX
+from greenlet.tests import TestCase
+from greenlet.tests.leakcheck import fails_leakcheck
+from greenlet.tests.leakcheck import ignores_leakcheck
+from greenlet.tests.leakcheck import RUNNING_ON_GITHUB_ACTIONS
+from greenlet.tests.leakcheck import RUNNING_ON_MANYLINUX

 try:
     from sys import intern
--- a/src/greenlet/tests/test_greenlet.py
+++ b/src/greenlet/tests/test_greenlet.py
@@ -10,8 +10,8 @@
 from abc import ABCMeta, abstractmethod

 from greenlet import greenlet
-from . import TestCase
-from .leakcheck import fails_leakcheck
+from greenlet.tests import TestCase
+from greenlet.tests.leakcheck import fails_leakcheck


 # We manually manage locks in many tests
--- a/src/greenlet/tests/test_generator_nested.py
+++ b/src/greenlet/tests/test_generator_nested.py
@@ -1,7 +1,7 @@

 from greenlet import greenlet
-from . import TestCase
-from .leakcheck import fails_leakcheck
+from greenlet.tests import TestCase
+from greenlet.tests.leakcheck import fails_leakcheck

 class genlet(greenlet):
     parent = None
--- a/src/greenlet/tests/test_generator.py
+++ b/src/greenlet/tests/test_generator.py
@@ -1,7 +1,7 @@

 from greenlet import greenlet

-from . import TestCase
+from greenlet.tests import TestCase

 class genlet(greenlet):
     parent = None
--- a/src/greenlet/tests/test_gc.py
+++ b/src/greenlet/tests/test_gc.py
@@ -5,8 +5,8 @@
 import greenlet


-from . import TestCase
-from .leakcheck import fails_leakcheck
+from greenlet.tests import TestCase
+from greenlet.tests.leakcheck import fails_leakcheck
 # These only work with greenlet gc support
 # which is no longer optional.
 assert greenlet.GREENLET_USE_GC
--- a/src/greenlet/tests/test_contextvars.py
+++ b/src/greenlet/tests/test_contextvars.py
@@ -9,7 +9,7 @@

 from greenlet import greenlet
 from greenlet import getcurrent
-from . import TestCase
+from greenlet.tests import TestCase


 try:
--- a/src/greenlet/tests/__init__.py
+++ b/src/greenlet/tests/__init__.py
@@ -21,7 +21,7 @@
 from greenlet._greenlet import get_pending_cleanup_count
 from greenlet._greenlet import get_total_main_greenlets

-from . import leakcheck
+from greenlet.tests import leakcheck


 class TestCaseMetaClass(type):
```

Here is pytest output with above patch:
<details>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-2.0.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-2.0.2-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -m 'not network' --import-mode=importlib
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.8.17, pytest-7.3.1, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2
collected 126 items

src/greenlet/tests/test_contextvars.py .........s                                                                                                                                     [  7%]
src/greenlet/tests/test_cpp.py .Fatal Python error: Aborted

Current thread 0x00007f84e8da7740 (most recent call first):
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 108 in run
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 315 in _bootstrap
  File "/usr/lib64/python3.8/multiprocessing/popen_fork.py", line 75 in _launch
  File "/usr/lib64/python3.8/multiprocessing/popen_fork.py", line 19 in __init__
  File "/usr/lib64/python3.8/multiprocessing/context.py", line 277 in _Popen
  File "/usr/lib64/python3.8/multiprocessing/context.py", line 224 in _Popen
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 121 in start
  File "/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_cpp.py", line 40 in _do_test_unhandled_exception
  File "/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_cpp.py", line 71 in test_unhandled_exception_aborts
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-2.0.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/leakcheck.py", line 212 in _run_test
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-2.0.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/leakcheck.py", line 294 in __call__
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-2.0.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/leakcheck.py", line 316 in wrapper
  File "/usr/lib64/python3.8/unittest/case.py", line 633 in _callTestMethod
  File "/usr/lib64/python3.8/unittest/case.py", line 676 in run
  File "/usr/lib64/python3.8/unittest/case.py", line 736 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/unittest.py", line 333 in runtest
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 169 in pytest_runtest_call
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 262 in <lambda>
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 341 in from_call
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 261 in call_runtest_hook
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 222 in call_and_report
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 133 in runtestprotocol
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 114 in pytest_runtest_protocol
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 323 in _main
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 166 in main
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 189 in console_main
  File "/usr/bin/pytest", line 8 in <module>
Fatal Python error: Aborted

Current thread 0x00007f84e8da7740 (most recent call first):
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 108 in run
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 315 in _bootstrap
  File "/usr/lib64/python3.8/multiprocessing/popen_fork.py", line 75 in _launch
  File "/usr/lib64/python3.8/multiprocessing/popen_fork.py", line 19 in __init__
  File "/usr/lib64/python3.8/multiprocessing/context.py", line 277 in _Popen
  File "/usr/lib64/python3.8/multiprocessing/context.py", line 224 in _Popen
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 121 in start
  File "/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_cpp.py", line 40 in _do_test_unhandled_exception
  File "/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_cpp.py", line 71 in test_unhandled_exception_aborts
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-2.0.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/leakcheck.py", line 212 in _run_test
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-2.0.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/leakcheck.py", line 294 in __call__
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-2.0.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/leakcheck.py", line 316 in wrapper
  File "/usr/lib64/python3.8/unittest/case.py", line 633 in _callTestMethod
  File "/usr/lib64/python3.8/unittest/case.py", line 676 in run
  File "/usr/lib64/python3.8/unittest/case.py", line 736 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/unittest.py", line 333 in runtest
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 169 in pytest_runtest_call
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 262 in <lambda>
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 341 in from_call
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 261 in call_runtest_hook
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 222 in call_and_report
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 133 in runtestprotocol
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 114 in pytest_runtest_protocol
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 323 in _main
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 166 in main
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 189 in console_main
  File "/usr/bin/pytest", line 8 in <module>
Fatal Python error: Aborted

Current thread 0x00007f84e8da7740 (most recent call first):
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 108 in run
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 315 in _bootstrap
  File "/usr/lib64/python3.8/multiprocessing/popen_fork.py", line 75 in _launch
  File "/usr/lib64/python3.8/multiprocessing/popen_fork.py", line 19 in __init__
  File "/usr/lib64/python3.8/multiprocessing/context.py", line 277 in _Popen
  File "/usr/lib64/python3.8/multiprocessing/context.py", line 224 in _Popen
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 121 in start
  File "/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_cpp.py", line 40 in _do_test_unhandled_exception
  File "/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_cpp.py", line 71 in test_unhandled_exception_aborts
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-2.0.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/leakcheck.py", line 212 in _run_test
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-2.0.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/leakcheck.py", line 294 in __call__
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-greenlet-2.0.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages/greenlet/tests/leakcheck.py", line 316 in wrapper
  File "/usr/lib64/python3.8/unittest/case.py", line 633 in _callTestMethod
  File "/usr/lib64/python3.8/unittest/case.py", line 676 in run
  File "/usr/lib64/python3.8/unittest/case.py", line 736 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/unittest.py", line 333 in runtest
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 169 in pytest_runtest_call
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 262 in <lambda>
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 341 in from_call
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 261 in call_runtest_hook
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 222 in call_and_report
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 133 in runtestprotocol
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 114 in pytest_runtest_protocol
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 323 in _main
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 166 in main
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 189 in console_main
  File "/usr/bin/pytest", line 8 in <module>
.Fatal Python error: Aborted

Current thread 0x00007f84e8da7740 (most recent call first):
<no Python frame>
Fatal Python error: Aborted

Current thread 0x00007f84e8da7740 (most recent call first):
<no Python frame>
Fatal Python error: Aborted

Current thread 0x00007f84e8da7740 (most recent call first):
<no Python frame>
.                                                                                                                                                    [ 10%]
src/greenlet/tests/test_extension_interface.py ...........                                                                                                                            [ 19%]
src/greenlet/tests/test_gc.py ....                                                                                                                                                    [ 22%]
src/greenlet/tests/test_generator.py .                                                                                                                                                [ 23%]
src/greenlet/tests/test_generator_nested.py .....                                                                                                                                     [ 26%]
src/greenlet/tests/test_greenlet.py ..F......................................................                                                                                         [ 72%]
src/greenlet/tests/test_greenlet_trash.py .                                                                                                                                           [ 73%]
src/greenlet/tests/test_leaks.py ............                                                                                                                                         [ 82%]
src/greenlet/tests/test_stack_saved.py .                                                                                                                                              [ 83%]
src/greenlet/tests/test_throw.py .......                                                                                                                                              [ 88%]
src/greenlet/tests/test_tracing.py ..........                                                                                                                                         [ 96%]
src/greenlet/tests/test_version.py .                                                                                                                                                  [ 97%]
src/greenlet/tests/test_weakref.py ...                                                                                                                                                [100%]

========================================================================================= FAILURES ==========================================================================================
________________________________________________________________ TestGreenlet.test_dealloc_catches_GreenletExit_throws_other ________________________________________________________________

self = <src.greenlet.tests.test_greenlet.TestGreenlet testMethod=test_dealloc_catches_GreenletExit_throws_other>

    def test_dealloc_catches_GreenletExit_throws_other(self):
        def run():
            try:
                greenlet.getcurrent().parent.switch()
            except greenlet.GreenletExit:
                raise SomeError

        g = greenlet(run)
        g.switch()
        # Destroying the only reference to the greenlet causes it
        # to get GreenletExit; when it in turn raises, even though we're the parent
        # we don't get the exception, it just gets printed.
        # When we run on 3.8 only, we can use sys.unraisablehook
        oldstderr = sys.stderr
        try:
            from cStringIO import StringIO
        except ImportError:
            from io import StringIO
        stderr = sys.stderr = StringIO()
        try:
            del g
        finally:
            sys.stderr = oldstderr

        v = stderr.getvalue()
>       self.assertIn("Exception", v)
E       AssertionError: 'Exception' not found in ''

src/greenlet/tests/test_greenlet.py:214: AssertionError
===================================================================================== warnings summary ======================================================================================
src/greenlet/tests/test_greenlet.py::TestGreenlet::test_dealloc_catches_GreenletExit_throws_other
  /usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <greenlet.greenlet object at 0x7f84e70b8240 (otid=0x7f84e6d99f00) dead>

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_greenlet.py", line 192, in run
      greenlet.getcurrent().parent.switch()
  greenlet.GreenletExit: Killing the greenlet because all references have vanished.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/greenlet-2.0.2/src/greenlet/tests/test_greenlet.py", line 194, in run
      raise SomeError
  src.greenlet.tests.test_greenlet.SomeError

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================== short test summary info ==================================================================================
SKIPPED [1] src/greenlet/tests/test_contextvars.py:287: ContextVar supported
FAILED src/greenlet/tests/test_greenlet.py::TestGreenlet::test_dealloc_catches_GreenletExit_throws_other - AssertionError: 'Exception' not found in ''
=================================================================== 1 failed, 124 passed, 1 skipped, 1 warning in 53.20s ====================================================================
```
</details>

Here is list of installed modules in build env
<details>

```console
Package                       Version
----------------------------- -------
alabaster                     0.7.13
asttokens                     2.2.1
Babel                         2.12.1
backcall                      0.2.0
build                         0.10.0
charset-normalizer            3.1.0
decorator                     5.1.1
distro                        1.8.0
docutils                      0.19
exceptiongroup                1.1.1
executing                     1.2.0
gpg                           1.20.0
graphviz                      0.20.1
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.6.0
iniconfig                     2.0.0
installer                     0.7.0
ipython                       8.12.0
jedi                          0.18.2
Jinja2                        3.1.2
libcomps                      0.1.19
MarkupSafe                    2.1.2
matplotlib-inline             0.1.6
objgraph                      3.5.0
packaging                     23.1
parso                         0.8.3
pexpect                       4.8.0
pickleshare                   0.7.5
pluggy                        1.0.0
prompt-toolkit                3.0.38
psutil                        5.9.2
ptyprocess                    0.7.0
pure-eval                     0.2.2
Pygments                      2.15.1
pyproject_hooks               1.0.0
pytest                        7.3.1
python-dateutil               2.8.2
pytz                          2023.2
requests                      2.31.0
setuptools                    67.7.2
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        6.2.1
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
stack-data                    0.6.2
tomli                         2.0.1
traitlets                     5.9.0
typing_extensions             4.5.0
urllib3                       1.26.15
wcwidth                       0.2.6
wheel                         0.40.0
zipp                          3.15.0
```
</details>

Please let me know if you want above patch as PR.

**Comment by jamadden** [comment]
Thank you for your interest in greenlet, but I am not going to accept in a patch that removes relative imports.

**Comment by kloczek** [comment]
Nevertheless all relative imports are messing with testing using pytest ..
